title: Dimitrios Vasilopoulos
#logo: /assets/img/logo.png
email: Dimitrios [dot] Vasilopoulos [at] eurecom [dot] fr
#description: 
show_downloads: false
#google_analytics: 
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0003-2237-9202
  - name: DBLP
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" ><title/><path d="M21.3 14.58l-2.45-9.16s-.15-.59-.72-.33l-5.6 2.6.86 3.2 1.09 4.08.01.06c.05.47-.41.79-.41.79l-1.88.87.5 1.89.04.1c.07.17.28.6.81.91l6.95 4.27s.68.41.52-.17l-1.98-7.4 1.86-.86s.56-.26.4-.85zM13.76 14.67l-.01-.06-1.13-4.22-.66-2.45-.67-2.49v-.04s-.16-.59-.84-1L3.5.14s-.68-.41-.52.17l1.99 7.42-1.87.87s-.56.26-.4.85l2.45 9.16s.16.59.72.33l6.17-2.87 1.3-.61s.52-.24.42-.79z"/></svg>
    link: https://dblp.org/pid/190/2075.html
  - name: Google Scholar
    icon: <i class="fa-brands fa-google-scholar"></i>
    link: https://scholar.google.com/citations?user=
  - name: My CV
    icon: <i class="fa-solid fa-download"></i>
    link: ./docs/cv-vasilopoulos-en.pdf

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
